name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    name: Test on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20, 22, 24]
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        run: yarn --ignore-engines
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
